//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.StudioCore.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.StudioCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;401 Unauthorized&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;center&gt;&lt;h1&gt;401 Unauthorized&lt;/h1&gt;&lt;/center&gt;
        ///    &lt;hr /&gt;
        ///    &lt;center&gt;SP.StudioCore/1.0.0.0&lt;/center&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string _401 {
            get {
                return ResourceManager.GetString("_401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--顶级域名列表--&gt;
        ///&lt;root&gt;
        ///	&lt;item&gt;.app&lt;/item&gt;
        ///	&lt;item&gt;.art&lt;/item&gt;
        ///	&lt;item&gt;.bid&lt;/item&gt;
        ///	&lt;item&gt;.bio&lt;/item&gt;
        ///	&lt;item&gt;.biz&lt;/item&gt;
        ///	&lt;item&gt;.cab&lt;/item&gt;
        ///	&lt;item&gt;.cam&lt;/item&gt;
        ///	&lt;item&gt;.ceo&lt;/item&gt;
        ///	&lt;item&gt;.com&lt;/item&gt;
        ///	&lt;item&gt;.dev&lt;/item&gt;
        ///	&lt;item&gt;.dog&lt;/item&gt;
        ///	&lt;item&gt;.fyi&lt;/item&gt;
        ///	&lt;item&gt;.how&lt;/item&gt;
        ///	&lt;item&gt;.ink&lt;/item&gt;
        ///	&lt;item&gt;.ist&lt;/item&gt;
        ///	&lt;item&gt;.law&lt;/item&gt;
        ///	&lt;item&gt;.lol&lt;/item&gt;
        ///	&lt;item&gt;.ltd&lt;/item&gt;
        ///	&lt;item&gt;.mba&lt;/item&gt;
        ///	&lt;item&gt;.men&lt;/item&gt;
        ///	&lt;item&gt;.moe&lt;/item&gt;
        ///	&lt;item&gt;.mom&lt;/item&gt;
        ///	&lt;item&gt;.n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Chinese&quot;: {
        ///    &quot;FirstName&quot;: [ &quot;支&quot;, &quot;余&quot;, &quot;贲&quot;, &quot;赵&quot;, &quot;慕&quot;, &quot;巫&quot;, &quot;太叔&quot;, &quot;方&quot;, &quot;诸&quot;, &quot;元&quot;, &quot;邓&quot;, &quot;孙&quot;, &quot;萧&quot;, &quot;乔&quot;, &quot;尉迟&quot;, &quot;柳&quot;, &quot;朱&quot;, &quot;卜&quot;, &quot;单&quot;, &quot;李&quot;, &quot;姚&quot;, &quot;燕&quot;, &quot;东方&quot;, &quot;叶&quot;, &quot;尤&quot;, &quot;顾&quot;, &quot;杭&quot;, &quot;周&quot;, &quot;邵&quot;, &quot;牧&quot;, &quot;诸葛&quot;, &quot;唐&quot;, &quot;许&quot;, &quot;穆&quot;, &quot;洪&quot;, &quot;郑&quot;, &quot;狄&quot;, &quot;侯&quot;, &quot;夏侯&quot;, &quot;吕&quot;, &quot;尹&quot;, &quot;包&quot;, &quot;王&quot;, &quot;宋&quot;, &quot;秋&quot;, &quot;欧阳&quot;, &quot;曹&quot;, &quot;堪&quot;, &quot;诸&quot;, &quot;冯&quot;, &quot;庞&quot;, &quot;仲&quot;, &quot;皇甫&quot;, &quot;严&quot;, &quot;汪&quot;, &quot;左&quot;, &quot;陈&quot;, &quot;叶&quot;, &quot;宫&quot;, &quot;上官&quot;, &quot;华&quot;, &quot;祁&quot;, &quot;石&quot;, &quot;卫&qu... 的本地化字符串。
        /// </summary>
        internal static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
    }
}
